In [9]:
import numpy as np

In [10]:
a = np.arange(0, 10)

In [11]:
print(a + a)

[ 0  2  4  6  8 10 12 14 16 18]


In [12]:
print(a * a)

[ 0  1  4  9 16 25 36 49 64 81]


In [13]:
print(a - a)

[0 0 0 0 0 0 0 0 0 0]


In [14]:
print(a / a)

[nan  1.  1.  1.  1.  1.  1.  1.  1.  1.]


/tmp/ipykernel_97/447378582.py:1: RuntimeWarning: invalid value encountered in true_divide
  print(a / a)


In [15]:
print(1/a)

[       inf 1.         0.5        0.33333333 0.25       0.2
 0.16666667 0.14285714 0.125      0.11111111]


/tmp/ipykernel_97/1221125316.py:1: RuntimeWarning: divide by zero encountered in true_divide
  print(1/a)


In [16]:
print(a**3)

[  0   1   8  27  64 125 216 343 512 729]


In [17]:
print(np.sqrt(a))

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]


In [18]:
print(np.exp(a))

[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03]


In [20]:
print(np.max(a))
print(a.max())

9
9


In [22]:
print(np.sin(a))

[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427
 -0.2794155   0.6569866   0.98935825  0.41211849]


In [23]:
print(np.log(a))

[      -inf 0.         0.69314718 1.09861229 1.38629436 1.60943791
 1.79175947 1.94591015 2.07944154 2.19722458]


/tmp/ipykernel_97/897204776.py:1: RuntimeWarning: divide by zero encountered in log
  print(np.log(a))
