In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [5]:
print(arr[8])

8


In [6]:
print(arr[1:5])

[1 2 3 4]


In [7]:
arr[0:5] = 100

In [8]:
print(arr)

[100 100 100 100 100   5   6   7   8   9  10]


In [9]:
arr = np.arange(0,11)

In [10]:
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [11]:
teil_arr = arr[0:6]

In [12]:
print(teil_arr)

[0 1 2 3 4 5]


In [13]:
teil_arr[:] = 99

In [14]:
print(teil_arr)

[99 99 99 99 99 99]


In [15]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [16]:
arr_copy = arr.copy()

In [17]:
print(arr_copy)

[99 99 99 99 99 99  6  7  8  9 10]


In [18]:
arr_2d = np.array(([5, 10, 15], [20, 25, 30], [35, 45, 45]))

In [19]:
print(arr_2d)

[[ 5 10 15]
 [20 25 30]
 [35 45 45]]


In [21]:
print(arr_2d[1])

[20 25 30]


In [23]:
print(arr_2d[1][0]) # alternative arr_2d[1, 0]

20


In [24]:
print(arr_2d[:2, 1:])

[[10 15]
 [25 30]]


In [25]:
print(arr_2d[2])

[35 45 45]


In [26]:
arr = np.arange(1,11)

In [27]:
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [30]:
bool_arr = arr > 5
print(bool_arr)

[False False False False False  True  True  True  True  True]


In [32]:
print(arr[arr>5])

[ 6  7  8  9 10]


In [33]:
x = 2

In [34]:
arr[arr > x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [35]:
arr_2d = np.arange(50).reshape(5, 10)

In [36]:
print(arr_2d)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]


In [38]:
print(arr_2d[1:3,3:5])

[[13 14]
 [23 24]]
