In [5]:
import numpy as np

In [6]:
l = [1, 2, 3]

In [7]:
print(l)

[1, 2, 3]


In [8]:
np.array(l)

array([1, 2, 3])

In [9]:
matrix = [[1, 2, 3], [4, 5, 6]]

In [10]:
print(matrix)

[[1, 2, 3], [4, 5, 6]]


In [11]:
np.array(matrix)

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(1, 11,2)

array([1, 3, 5, 7, 9])

In [14]:
np.zeros(4)

array([0., 0., 0., 0.])

In [15]:
np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
np.ones((3))

array([1., 1., 1.])

In [17]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [18]:
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

In [19]:
np.linspace(0, 10)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [20]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [21]:
np.random.rand(2)

array([0.23423808, 0.76580747])

In [22]:
np.random.rand(5, 5)

array([[0.48000878, 0.07168492, 0.56127334, 0.38803971, 0.87371565],
       [0.09572821, 0.13037411, 0.72296484, 0.55488098, 0.25967167],
       [0.1310137 , 0.262462  , 0.97471948, 0.07351045, 0.12370024],
       [0.05407359, 0.971782  , 0.7833147 , 0.76959139, 0.28978929],
       [0.96844433, 0.51164869, 0.21883137, 0.30052765, 0.86884281]])

In [23]:
np.random.randint(1,100)

7

In [24]:
np.random.randint(1,100, 10)

array([66, 36, 85, 96, 10, 56, 10, 13, 35, 96])

In [29]:
arr = np.arange(25)

In [30]:
ranarr = np.random.randint(0, 50, 10)

In [33]:
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


In [32]:
print(ranarr)

[28 30 16 12 44 34  4 31 47  1]


In [34]:
arr.reshape(5,5) # zahlen müssen übereinstimmen

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [35]:
ranarr.max()

47

In [36]:
ranarr.argmax()

8

In [37]:
ranarr.min()

1

In [38]:
ranarr.argmin()

9

In [39]:
arr.shape

(25,)

In [40]:
ranarr.shape

(10,)

In [41]:
arr.dtype

dtype('int64')